// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class add_aboutstatus_mig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_aboutstatus_mig));
        
        string IMigrationMetadata.Id
        {
            get { return "202605061625367_add_aboutstatus_mig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
