// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class add_adminstatus_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_adminstatus_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "202605121804375_add_admin-status_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
