// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class add_isread_add_messagetable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_isread_add_messagetable));
        
        string IMigrationMetadata.Id
        {
            get { return "202605061655578_add_isread_add_message-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
