// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class add_skill_cardabout : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_skill_cardabout));
        
        string IMigrationMetadata.Id
        {
            get { return "202605131643073_add_skill_card-about"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
